This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./proyecto.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file proyecto.acn....done (232 entries accepted, 0 rejected).
Sorting entries.....done (1922 comparisons).
Generating output file proyecto.acr....done (112 lines written, 0 warnings).
Output written in proyecto.acr.
Transcript written in proyecto.alg.
